FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
	build-essential \
	&& rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pandas redis

COPY . .

CMD ["python","-u","engine.py"]

ENV PYTHONUNBUFFERED=1


